<?php

namespace Database\Seeders;

use App\Models\Make;
use Illuminate\Database\Seeder;

class MakeSeeder extends Seeder
{
    public function run(): void
    {
        $makes = [
            ['name' => 'Toyota',      'display_order' => 1],
            ['name' => 'Nissan',      'display_order' => 2],
            ['name' => 'Mitsubishi',  'display_order' => 3],
            ['name' => 'Honda',       'display_order' => 4],
            ['name' => 'Hyundai',     'display_order' => 5],
            ['name' => 'Kia',         'display_order' => 6],
            ['name' => 'Ford',        'display_order' => 7],
            ['name' => 'Chevrolet',   'display_order' => 8],
            ['name' => 'GMC',         'display_order' => 9],
            ['name' => 'Jeep',        'display_order' => 10],
            ['name' => 'Dodge',       'display_order' => 11],
            ['name' => 'BMW',         'display_order' => 12],
            ['name' => 'Mercedes-Benz', 'display_order' => 13],
            ['name' => 'Audi',        'display_order' => 14],
            ['name' => 'Volkswagen',  'display_order' => 15],
            ['name' => 'Land Rover',  'display_order' => 16],
            ['name' => 'Lexus',       'display_order' => 17],
            ['name' => 'Infiniti',    'display_order' => 18],
            ['name' => 'Mazda',       'display_order' => 19],
            ['name' => 'Suzuki',      'display_order' => 20],
        ];

        foreach ($makes as $data) {
            Make::firstOrCreate(
                ['name' => $data['name']],
                array_merge($data, ['is_active' => true])
                // Slug is auto-generated by Spatie Sluggable on create
            );
        }
    }
}
